name: Law Office Management System Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run installation test
      run: python test_installation.py

    - name: Test imports
      run: |
        python -c "import tkinter; print('tkinter OK')"
        python -c "import sqlite3; print('sqlite3 OK')"
        python -c "import bcrypt; print('bcrypt OK')"
        python -c "import arabic_reshaper; print('arabic_reshaper OK')"
        python -c "from bidi.algorithm import get_display; print('python-bidi OK')"

    - name: Test database creation
      run: |
        python -c "
        import sqlite3
        import os
        os.makedirs('data', exist_ok=True)
        conn = sqlite3.connect('data/test.db')
        conn.execute('CREATE TABLE test (id INTEGER PRIMARY KEY)')
        conn.close()
        print('Database test OK')
        "

    - name: Test Arabic text processing
      run: |
        python -c "
        import arabic_reshaper
        from bidi.algorithm import get_display
        text = 'نظام إدارة مكتب المحاماة'
        reshaped = arabic_reshaper.reshape(text)
        bidi_text = get_display(reshaped)
        print('Arabic processing OK:', bidi_text)
        "

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
        pip install -r requirements.txt
    
    - name: Run security checks with bandit
      run: bandit -r . -f json -o bandit-report.json || true
    
    - name: Check for known security vulnerabilities
      run: safety check --json || true